export const codPais = [
    // Prioritarios
    { code: 'GT', name: 'Guatemala', callingCode: '502', emoji: '🇬🇹' },
    { code: 'US', name: 'Estados Unidos', callingCode: '1', emoji: '🇺🇸' },
    { code: 'MX', name: 'México', callingCode: '52', emoji: '🇲🇽' },
  
    // Otros países latinoamericanos
    { code: 'CO', name: 'Colombia', callingCode: '57', emoji: '🇨🇴' },
    { code: 'CL', name: 'Chile', callingCode: '56', emoji: '🇨🇱' },
    { code: 'PE', name: 'Perú', callingCode: '51', emoji: '🇵🇪' },
    { code: 'AR', name: 'Argentina', callingCode: '54', emoji: '🇦🇷' },
    { code: 'ES', name: 'España', callingCode: '34', emoji: '🇪🇸' },
    { code: 'CR', name: 'Costa Rica', callingCode: '506', emoji: '🇨🇷' },
    { code: 'SV', name: 'El Salvador', callingCode: '503', emoji: '🇸🇻' },
    { code: 'HN', name: 'Honduras', callingCode: '504', emoji: '🇭🇳' },
    { code: 'NI', name: 'Nicaragua', callingCode: '505', emoji: '🇳🇮' },
    { code: 'PA', name: 'Panamá', callingCode: '507', emoji: '🇵🇦' },
    { code: 'EC', name: 'Ecuador', callingCode: '593', emoji: '🇪🇨' },
    { code: 'VE', name: 'Venezuela', callingCode: '58', emoji: '🇻🇪' },
    { code: 'BR', name: 'Brasil', callingCode: '55', emoji: '🇧🇷' },
    { code: 'DO', name: 'República Dominicana', callingCode: '1809/1829/1849', emoji: '🇩🇴' },
    { code: 'CU', name: 'Cuba', callingCode: '53', emoji: '🇨🇺' },
    { code: 'PR', name: 'Puerto Rico', callingCode: '1787/1939', emoji: '🇵🇷' },
    { code: 'BO', name: 'Bolivia', callingCode: '591', emoji: '🇧🇴' },
    { code: 'PY', name: 'Paraguay', callingCode: '595', emoji: '🇵🇾' },
    { code: 'UY', name: 'Uruguay', callingCode: '598', emoji: '🇺🇾' },
    { code: 'EC', name: 'Ecuador', callingCode: '593', emoji: '🇪🇨' },
    { code: 'GF', name: 'Guayana Francesa', callingCode: '594', emoji: '🇬🇫' },
    { code: 'GP', name: 'Guadalupe', callingCode: '590', emoji: '🇬🇵' },
    { code: 'HT', name: 'Haití', callingCode: '509', emoji: '🇭🇹' },
    { code: 'JM', name: 'Jamaica', callingCode: '1876', emoji: '🇯🇲' },
    { code: 'BS', name: 'Bahamas', callingCode: '1242', emoji: '🇧🇸' },
    { code: 'BB', name: 'Barbados', callingCode: '1246', emoji: '🇧🇧' },
    { code: 'TT', name: 'Trinidad y Tobago', callingCode: '1868', emoji: '🇹🇹' },
    { code: 'DM', name: 'Dominica', callingCode: '1767', emoji: '🇩🇲' },
    { code: 'AG', name: 'Antigua y Barbuda', callingCode: '1268', emoji: '🇦🇬' },
    { code: 'KN', name: 'San Cristóbal y Nieves', callingCode: '1869', emoji: '🇰🇳' },
    { code: 'LC', name: 'Santa Lucía', callingCode: '1758', emoji: '🇱🇨' },
    { code: 'VC', name: 'San Vicente y las Granadinas', callingCode: '1784', emoji: '🇻🇨' }
  ]